import type { Lesson } from "../../types";

// Phase 8 — Lesson 2: Humor & Irony
// Prosodic humor — sarcasm (fall-rise + stretch), deadpan (flat/low), self-deprecation
// (falling/soft/mock-sad), hyperbole (wide swings). No puns. Purely acoustic.
// 12 steps: intro, concept, concept, intonation, intonation, example, tap-pronounce,
// rhythm, tip, practice, quiz, completion.

const lesson: Lesson = {
  id: "p8l2",
  phaseId: 7,
  lessonIndex: 1,
  title: "Humor & Irony",
  subtitle: "Make natives laugh — sarcasm, deadpan, and self-deprecation that actually lands",
  duration: 12,
  xp: 190,
  objectives: [
    "Produce the four prosodic flavors of English humor: sarcastic, deadpan, self-deprecating, hyperbolic",
    "Shape the fall-rise contour and vowel stretch that signal irony",
    "Distinguish sincere vs sarcastic delivery of identical words",
    "Time the deadpan pause so absurd content lands as funny, not awkward",
  ],
  steps: [
    {
      id: "intro",
      type: "intro",
      title: "Humor & Irony",
      subtitle: "Funny isn't about the words — it's about the contour",
      description:
        "English humor lives in prosody, not punchlines. The line 'Oh, great' can mean 'I'm delighted' or 'this is a disaster' — and the only difference is the shape of the pitch. Sarcasm stretches a vowel and flips the contour; deadpan flattens everything to a low monotone so the absurdity speaks for itself; self-deprecation falls softly, half-apologetic; hyperbole swings wide. A learner who masters these four shapes gets laughs. A learner who doesn't gets confused silences — or worse, taken literally. This lesson teaches you the acoustic signatures of prosodic humor and trains your mouth to produce them on cue.",
      visual: "intonation",
      emoji: "😏",
    },
    {
      id: "concept-1",
      type: "concept",
      title: "The Four Flavors of Prosodic Humor",
      body: [
        "Spoken English has four prosodic modes for humor, each with a distinct acoustic fingerprint. Sarcasm says the opposite of what it means via a fall-rise contour — pitch drops low, then bounces back up, usually with the stressed vowel stretched longer than normal. Deadpan delivers absurd or extreme content in a flat, low, monotone voice — the gap between words and tone is the joke. Self-deprecation uses a soft, falling, mock-sad contour, as if apologizing for your own existence. Hyperbole swings pitch wildly high and low, exaggerating stress on emotional words to make everything seem larger than life.",
        "These four modes are not interchangeable. Use sarcasm and the listener reads irony; use deadpan and they read dry wit; use self-deprecation and they read humility-as-comedy; use hyperbole and they read exaggeration-as-comedy. Picking the wrong mode — say, hyperbolic delivery on a sarcastic line — produces confusion instead of laughs. The good news: each mode is just a contour shape, and shapes can be drilled. Train your mouth to make the four shapes, and your brain will pick the right one for each joke automatically.",
      ],
      bulletPoints: [
        "SARCASM — fall-rise contour, stressed vowel lengthened, exaggerated stress",
        "DEADPAN — flat, low, monotone delivery of absurd content (contrast = joke)",
        "SELF-DEPRECATION — falling, soft, mock-sad, half-apologetic",
        "HYPERBOLE — wide pitch swings, exaggerated stress, larger-than-life vowels",
        "IRONY in general — say opposite of meaning, signal via contour shape",
      ],
      visual: "phoneme-grid",
      visualLabel: "Four acoustic fingerprints of English humor",
    },
    {
      id: "concept-2",
      type: "concept",
      title: "Why Sarcasm Sounds Sarcastic — The Acoustic Tells",
      body: [
        "Researchers have identified three reliable acoustic markers of English sarcasm. First, the contour: a fall-rise pattern — pitch drops low on the stressed word, then bounces up at the end, the inverse of a sincere declarative fall. Second, vowel lengthening: the stressed vowel is held 30–60% longer than in sincere speech (think 'Greaaat' instead of 'Great'). Third, lower average pitch: sarcastic utterances sit lower in the speaker's range than their sincere equivalents, often with a nasal or hollow resonance. Together these three tells — fall-rise + stretch + low pitch — make sarcasm instantly recognizable to native ears.",
        "This explains why learners often miss sarcasm: their ears are trained on the words, not the contour. It also explains why learners' own attempts at sarcasm fall flat — they say the words sarcastically in their head, but their mouth produces a sincere contour. The fix is mechanical: deliberately lower your pitch, deliberately stretch the stressed vowel, deliberately let the pitch bounce back up at the end. Exaggerate at first — make it cartoonish — and let your mouth learn the shape. Once the muscle memory is there, you can dial the exaggeration down to a natural level.",
      ],
      bulletPoints: [
        "Tell 1 — fall-rise contour (drop low, bounce up)",
        "Tell 2 — stressed vowel held 30–60% longer than normal",
        "Tell 3 — lower average pitch than sincere equivalent",
        "Bonus — slight nasal/hollow resonance adds irony",
        "Drill — exaggerate first, dial back to natural once muscle memory forms",
      ],
      visual: "intonation",
      visualLabel: "Sincere fall vs sarcastic fall-rise",
    },
    {
      id: "intonation-sarcasm",
      type: "intonation",
      title: "Sarcastic Fall-Rise — 'Oh, great.'",
      phrase: "Oh, great. Another Monday.",
      contour: [
        { x: 5, y: 55 },
        { x: 12, y: 70 },
        { x: 20, y: 35 },
        { x: 30, y: 22 },
        { x: 38, y: 28 },
        { x: 48, y: 45 },
        { x: 58, y: 60 },
        { x: 68, y: 38 },
        { x: 78, y: 48 },
        { x: 88, y: 58 },
        { x: 95, y: 65 },
      ],
      pattern: "fall-rise",
      description:
        "The sarcastic 'Oh, great.' contour is the inverse of sincere. Pitch rises briefly on 'Oh' (y 55→70), then DROPS hard on 'great' (y 70→22) — the vowel is held long here, drawn out into a 'greaaat' — then bounces back UP at the end (y 22→65). The fall-rise bounce on 'great' is the sarcasm signature. 'Another Monday' continues low and rises again at the end. Native ears hear the bounce and instantly read irony, even without context.",
    },
    {
      id: "intonation-deadpan",
      type: "intonation",
      title: "Deadpan Level — 'Wow. Fun.'",
      phrase: "Wow. Fun. Can't wait.",
      contour: [
        { x: 5, y: 32 },
        { x: 15, y: 30 },
        { x: 25, y: 33 },
        { x: 35, y: 28 },
        { x: 45, y: 31 },
        { x: 55, y: 29 },
        { x: 65, y: 32 },
        { x: 75, y: 30 },
        { x: 85, y: 33 },
        { x: 95, y: 28 },
      ],
      pattern: "level",
      description:
        "Deadpan humor is acoustic minimalism. Pitch stays in a tiny band (y 28–33) — essentially flat and low. There are no rises, no falls, no stress peaks. The words 'Wow. Fun. Can't wait.' are enthusiastic in their literal meaning, but the flat low contour signals the opposite: 'I am not excited at all.' The comedy comes from the GAP between the enthusiastic words and the dead-flat delivery. Without the gap, it's just an enthusiastic sentence. With the gap, it's dry wit. Hold your face still, too — deadpan requires both voice and expression to be flat.",
    },
    {
      id: "example-selfdep",
      type: "example",
      title: "Self-Deprecation in Action",
      phrase: "So yeah, that's me — three years of Spanish, and I just ordered a 'glass of bird' in Madrid. Smooth.",
      ipa: "/soʊ jeə ðæts miː θriː jɪrz əv ˈspænɪʃ ænd aɪ dʒʌst ˈɔrdərd ə ɡlæs əv bɜrd ɪn məˈdrɪd smuːθ/",
      highlightWords: ["me", "three", "Spanish", "ordered", "bird", "Madrid", "Smooth"],
      tip: "Self-deprecation uses a falling, soft, mock-sad contour — like you're playfully apologizing for your own incompetence. 'So yeah, that's me' is delivered low and gentle. The setup builds matter-of-factly. The punch word 'Smooth' falls to the bottom of your range and lingers there — the mock-resignation is the joke. The prosody says 'I am disappointed in myself' while the words say 'I did something ridiculous.' That contrast is the engine of self-deprecating humor.",
      tapWords: [
        { word: "me", ipa: "/miː/" },
        { word: "Spanish", ipa: "/ˈspænɪʃ/" },
        { word: "ordered", ipa: "/ˈɔrdərd/" },
        { word: "bird", ipa: "/bɜrd/" },
        { word: "Smooth", ipa: "/smuːθ/" },
      ],
    },
    {
      id: "tap-pronounce-pairs",
      type: "tap-pronounce",
      title: "Sincere vs Sarcastic — Same Words, Two Contours",
      description: "Tap each pair. Same exact words — opposite meanings, signaled only by prosody. Notice the vowel stretch and the fall-rise bounce on the sarcastic versions.",
      words: [
        { word: "Great. (sincere)", ipa: "/ɡreɪt/", meaning: "high-falling, short vowel, genuine delight" },
        { word: "Greaaat. (sarcastic)", ipa: "/ɡreɪːːt/", meaning: "fall-rise, stretched vowel, ironic dread" },
        { word: "Oh, fun. (genuine)", ipa: "/oʊ fʌn/", meaning: "rising on 'fun', bright, real enthusiasm" },
        { word: "Oh, fun. (deadpan)", ipa: "/oʊ fʌn/", meaning: "flat low monotone, no enthusiasm at all" },
        { word: "Wow, amazing. (genuine)", ipa: "/waʊ əˈmeɪzɪŋ/", meaning: "high peak on 'a-', real excitement" },
        { word: "Wow, amazing. (sarcastic)", ipa: "/waʊ əˈmeɪzɪŋ/", meaning: "fall-rise, stretch on 'a-', ironic dismissal" },
        { word: "Nice going. (sincere praise)", ipa: "/naɪs ˈɡoʊɪŋ/", meaning: "rising-falling, warm tone" },
        { word: "Nice going. (sarcastic blame)", ipa: "/naɪs ˈɡoʊɪŋ/", meaning: "fall-rise, low, stretch on 'nice'" },
      ],
    },
    {
      id: "rhythm-hyperbole",
      type: "rhythm",
      title: "Hyperbole Beat Map — 'Best. Day. Ever.'",
      phrase: "Best. Day. Ever. I mean, are you kidding me right now?",
      beats: [
        { text: "Best.", duration: 2.2, stressed: true },
        { text: "Day.", duration: 2.0, stressed: true },
        { text: "Ev-", duration: 1.4, stressed: true },
        { text: "er.", duration: 1.6, stressed: false },
        { text: "I", duration: 0.6, stressed: false },
        { text: "mean,", duration: 0.8, stressed: false },
        { text: "are", duration: 0.5, stressed: false },
        { text: "you", duration: 0.6, stressed: false },
        { text: "KID-", duration: 1.8, stressed: true },
        { text: "ding", duration: 0.7, stressed: false },
        { text: "me", duration: 0.7, stressed: false },
        { text: "right", duration: 0.6, stressed: false },
        { text: "now?", duration: 1.0, stressed: false },
      ],
      description:
        "Hyperbole exaggerates both stress AND duration. 'Best. Day. Ev-er.' gets three heavy beats with stretched durations — the words punch out one at a time like drum hits, and 'Ev-' is held extra long with a wide pitch swing up. The setup 'I mean, are you' compresses to fast unstressed beats, then 'KID-' explodes as a huge stressed peak, the comic climax. Wide swings between heavy and light beats is the rhythm signature of hyperbole — every stress feels bigger than life.",
    },
    {
      id: "tip-1",
      type: "tip",
      title: "💡 Native Trick — The Face Holds the Punchline",
      body: "Prosodic humor only lands if your face agrees with your voice. Sarcasm needs a slight eye-roll or one raised eyebrow; deadpan needs an absolutely still, neutral face — no smile, no blink; self-deprecation needs a small shrug or half-smile; hyperbole needs wide eyes and an open mouth. If your voice is sarcastic but your face is smiling genuinely, the listener's brain gets mixed signals and the joke dies. Train yourself to hold the matching facial expression while you produce the contour — record yourself on video and check: does your face match the prosody? If yes, the joke lands. If no, fix the face first, then the voice will follow.",
      variant: "success",
    },
    {
      id: "practice",
      type: "practice",
      title: "Deliver All Four Modes",
      phrase: "Oh, perfect. Just what I needed.",
      ipa: "/oʊ ˈpɜrfɪkt dʒʌst wʌt aɪ ˈniːdɪd/",
      tip: "Say this phrase four ways and feel the mouth-shape difference each time: (1) SINCERE — bright, high, falling on 'perfect', genuine pleasure. (2) SARCASTIC — low pitch, stretch 'purrrfect' into a long vowel, fall-rise bounce on 'needed'. (3) DEADPAN — flat, low, monotone, no expression, pause between words. (4) HYPERBOLIC — big pitch swings, heavy stress on 'perfect' and 'needed', wide-eyed delivery. Record all four — the words are identical but the mouth shape and prosody should be visibly different each time.",
      passScore: 80,
    },
    {
      id: "quiz",
      type: "quiz",
      question: "A coworker says 'Nice work' after you accidentally deleted the team's shared document. Which prosody signals that they are being sarcastic, not sincere?",
      options: [
        "High pitch, rising contour on 'Nice', short vowel, warm smile",
        "Low pitch, fall-rise contour on 'Nice' with the vowel stretched longer than normal, flat or slightly raised-eyebrow expression",
        "Flat low monotone on both words, no stress peaks, completely still face",
        "Wide pitch swings, exaggerated stress on both 'Nice' and 'work', big open smile",
      ],
      correct: 1,
      explanation:
        "Option 2 is the textbook sarcastic profile — the three acoustic tells of sarcasm are (1) fall-rise contour, (2) stressed vowel lengthened, and (3) lower average pitch than the sincere equivalent. Stretched 'Niiiice' with a fall-rise bounce reads instantly as irony. Option 1 is the sincere profile (high, rising, warm). Option 3 is deadpan — which works for dry humor but is the wrong mode here because 'Nice work' is not absurd content; it needs the contrast of a normally positive phrase delivered ironically. Option 4 is hyperbole — it would read as over-the-top praise, not sarcasm. Sarcasm specifically wants the fall-rise + stretch + low pitch signature.",
    },
    {
      id: "completion",
      type: "completion",
      title: "Humor & Irony Complete!",
      subtitle: "You can now produce the four prosodic flavors of English humor — sarcastic fall-rise, deadpan flat, self-deprecating fall, and hyperbolic wide swings — and your face matches your voice. Natives will start laughing with you, not at you.",
      xp: 190,
      badge: "😏 Irony Master",
      nextLessonTitle: "Regional Variants",
    },
  ],
};

export default lesson;
