import type { Lesson } from "../../types";

// Phase 7 — Lesson 2: Presentation Skills
// Pacing, pausing, emphasis for presentations. Rhythm beats with varied durations. Intonation for emphasis.
// 11 steps: intro, concept, concept, rhythm, intonation, example, tip, tap-pronounce, practice, quiz, completion.

const lesson: Lesson = {
  id: "p7l2",
  phaseId: 6,
  lessonIndex: 1,
  title: "Presentation Skills",
  subtitle: "Pacing, pausing, and emphasis that hold a room",
  duration: 11,
  xp: 165,
  objectives: [
    "Master presentation pacing: deliberate tempo with strategic pauses",
    "Use pitch emphasis to mark key terms and signal transitions",
    "Breathe at punctuation marks to anchor phrasing",
    "Open a presentation with authority and audience engagement",
  ],
  steps: [
    {
      id: "intro",
      type: "intro",
      title: "Presentation Skills",
      subtitle: "Speak so a room of strangers leans in",
      description:
        "A presentation is not a longer conversation — it is a different speech act entirely. Native presenters slow down, pause deliberately, and use pitch to mark what matters. Learners tend to rush, flatten pitch, and breathe shallowly. This lesson teaches the three pillars of presentation prosody: pacing, pausing, and emphasis. Master them and a room of strangers will lean in.",
      visual: "rhythm",
      emoji: "🎤",
    },
    {
      id: "concept-1",
      type: "concept",
      title: "Pacing — Slower Than You Think",
      body: [
        "The single most common mistake non-native presenters make is speaking too fast. On stage, your mouth feels slow because you can hear every word. To the audience, that 'slow' pace is normal — and the 'normal' pace you instinctively fall into is too fast to absorb. Native presenters aim for 120–140 words per minute: slower than conversation, much slower than you feel is natural.",
        "The fix is not just tempo — it is rhythm. A presentation breathes. You speak a phrase, pause, speak another. The pauses carry meaning: they let the audience digest, they signal structure ('here comes the key point'), and they project calm. A presentation without pauses feels like a wall of noise; a presentation with deliberate pauses feels authoritative.",
      ],
      bulletPoints: [
        "TEMPO: 120–140 wpm — slower than conversation, slower than feels natural",
        "PAUSE at every comma and full stop — at least one full beat",
        "PAUSE longer before a key term — it signals 'listen up'",
        "PAUSE longest at section breaks — three to five beats",
        "If you feel slow, you are probably right. If you feel normal, slow down.",
      ],
      visual: "rhythm",
      visualLabel: "Phrase — pause — phrase rhythm",
    },
    {
      id: "concept-2",
      type: "concept",
      title: "Emphasis — Pitch Marks Importance",
      body: [
        "In English, important words get a pitch jump — not just louder, but higher. This is how audiences know which word to remember. 'We grew 40% last year' places the jump on '40%'. 'We grew 40% last year' (jump on 'last year') means something different: it implies 'unlike the year before'. The pitch contour is the meaning.",
        "Native presenters use three emphasis tools: pitch jump (higher on the key word), lengthening (stretching the vowel), and post-stress pause (a beat of silence after the key word). Combine all three and the word becomes unforgettable. Use them too often and they lose power — reserve them for the two or three phrases per presentation that you want the audience to repeat.",
      ],
      bulletPoints: [
        "PITCH JUMP — go up a third or fifth on the key word, then return",
        "LENGTHENING — stretch the stressed vowel of the key word (~50% longer)",
        "POST-STRESS PAUSE — one beat of silence after the key word",
        "RESERVE emphasis for 2–3 phrases per presentation, not every sentence",
        "NEVER emphasize function words (the, of, is) — only content words",
      ],
      visual: "intonation",
      visualLabel: "Pitch jumps on key terms",
    },
    {
      id: "rhythm-opening",
      type: "rhythm",
      title: "Presentation Opening Rhythm",
      phrase: "Good morning, everyone. Today, I want to share three ideas that will change how you think about your work.",
      beats: [
        { text: "Good", duration: 1, stressed: false },
        { text: "MOR", duration: 2, stressed: true },
        { text: "ning", duration: 1, stressed: false },
        { text: "—", duration: 2, stressed: false },
        { text: "every", duration: 1, stressed: false },
        { text: "one", duration: 1, stressed: false },
        { text: "—", duration: 3, stressed: false },
        { text: "To", duration: 1, stressed: false },
        { text: "day", duration: 1, stressed: false },
        { text: "—", duration: 1, stressed: false },
        { text: "I", duration: 1, stressed: false },
        { text: "want", duration: 1, stressed: false },
        { text: "to", duration: 1, stressed: false },
        { text: "SHARE", duration: 2, stressed: true },
        { text: "—", duration: 1, stressed: false },
        { text: "THREE", duration: 2, stressed: true },
        { text: "i", duration: 1, stressed: false },
        { text: "deas", duration: 1, stressed: false },
        { text: "—", duration: 2, stressed: false },
        { text: "that", duration: 1, stressed: false },
        { text: "will", duration: 1, stressed: false },
        { text: "CHANGE", duration: 2, stressed: true },
        { text: "how", duration: 1, stressed: false },
        { text: "you", duration: 1, stressed: false },
        { text: "think", duration: 1, stressed: false },
        { text: "a", duration: 1, stressed: false },
        { text: "bout", duration: 1, stressed: false },
        { text: "your", duration: 1, stressed: false },
        { text: "WORK", duration: 2, stressed: true },
        { text: "—", duration: 3, stressed: false },
      ],
      description:
        "Notice the varied beat durations: stressed words (MORNING, SHARE, THREE, CHANGE, WORK) get duration 2, unstressed function words get duration 1, and the dashes (—) are deliberate pauses (duration 1–3). The three-beat pause after 'everyone' sets the audience; the two-beat pause before 'THREE' builds anticipation. Varying durations create rhythm — equal durations create monotone.",
    },
    {
      id: "intonation-emphasis",
      type: "intonation",
      title: "Emphasis Contour on a Key Term",
      phrase: "This is the single most important takeaway.",
      contour: [
        { x: 5, y: 35 },
        { x: 12, y: 40 },
        { x: 20, y: 38 },
        { x: 28, y: 42 },
        { x: 35, y: 45 },
        { x: 42, y: 50 },
        { x: 50, y: 80 },
        { x: 58, y: 90 },
        { x: 65, y: 75 },
        { x: 75, y: 55 },
        { x: 88, y: 35 },
        { x: 100, y: 25 },
      ],
      pattern: "rise-fall",
      description:
        "The pitch climbs gently through 'This is the single most' (y 35–50), then JUMPS to peak at 'im-POR-tant' (y 80–90), then falls through 'takeaway' (y 55–25). That jump on 'POR' is the emphasis — the audience hears it as 'remember this word'. The post-peak fall is what makes the emphasis land; a peak without a fall sounds like a question.",
    },
    {
      id: "example-opening",
      type: "example",
      title: "Presentation Opening Example",
      phrase: "Good morning. Thank you for being here. What I'm going to show you today is going to save your team twenty hours a week.",
      ipa: "/ɡʊd ˈmɔːrnɪŋ ˈθæŋk juː fɔːr ˈbiːɪŋ hɪər wɒt aɪm ˈɡoʊɪŋ tuː ʃoʊ juː təˈdeɪ ɪz ˈɡoʊɪŋ tuː seɪv jɔːr tiːm ˈtwɛnti ˈaʊərz ə wiːk/",
      highlightWords: ["Good", "morning", "Thank", "save", "twenty", "hours", "week"],
      tip: "Pause after every sentence — at least one full beat. The phrase 'twenty hours a week' should hit a pitch peak on 'twenty' and fall on 'week'. Avoid the temptation to say 'gonna' here — full 'going to' sounds deliberate and professional. The opening sets the rhythm for the entire talk.",
      tapWords: [
        { word: "Good morning", ipa: "/ɡʊd ˈmɔːrnɪŋ/" },
        { word: "Thank you for being here", ipa: "/ˈθæŋk juː fɔːr ˈbiːɪŋ hɪər/" },
        { word: "twenty hours a week", ipa: "/ˈtwɛnti ˈaʊərz ə wiːk/" },
      ],
    },
    {
      id: "tip-1",
      type: "tip",
      title: "💡 Native Trick — Breathe at Punctuation",
      body: "Every comma, full stop, and paragraph break in your script is a breathing opportunity. Take it. Inhale through your nose on every comma; inhale deeply through your nose on every full stop. This does three things at once: (1) it forces you to pause — which the audience needs; (2) it oxygenates you so you do not run out of breath mid-sentence; (3) it slows your heart rate, which calms you. Most learners hold their breath when nervous, then rush to finish before they suffocate. Breathe at punctuation and the talk breathes with you.",
      variant: "success",
    },
    {
      id: "tap-pronounce",
      type: "tap-pronounce",
      title: "Presentation Transition Words",
      description: "Tap each transition. These phrases signal structure to the audience — pronounce them crisply.",
      words: [
        { word: "Moving on to...", ipa: "/ˈmuːvɪŋ ɒn tuː/", meaning: "signals next section" },
        { word: "As I mentioned earlier...", ipa: "/æz aɪ ˈmɛnʃənd ˈɜːrliər/", meaning: "callback to previous point" },
        { word: "To put this in perspective...", ipa: "/tuː pʊt ðɪs ɪn pərˈspɛktɪv/", meaning: "frames scale or context" },
        { word: "Let me give you an example.", ipa: "/lɛt miː ɡɪv juː ən ɪɡˈzæmpəl/", meaning: "introduces illustration" },
        { word: "In conclusion...", ipa: "/ɪn kənˈkluːʒən/", meaning: "signals end" },
        { word: "The key takeaway is...", ipa: "/ðə kiː ˈteɪkəweɪ ɪz/", meaning: "marks the most important point" },
      ],
    },
    {
      id: "practice",
      type: "practice",
      title: "Deliver a Key Sentence",
      phrase: "The most important thing to remember is this: speed kills projects.",
      ipa: "/ðə moʊst ɪmˈpɔːrtənt θɪŋ tuː rɪˈmɛmbər ɪz ðɪs spiːd kɪlz ˈprɒdʒɛkts/",
      tip: "Climb gently through 'The most important thing to remember' — y 35 to 50. Hold the pitch on 'is this' (slight rise). Then PAUSE one beat. Then hit the peak on 'SPEED' (jump up to y 85), fall through 'kills', and end low on 'projects' (y 25). The pause before the punchline is non-negotiable — it is what makes the punchline land.",
      passScore: 80,
    },
    {
      id: "quiz",
      type: "quiz",
      question: "You're delivering this sentence: 'We grew revenue by forty percent last quarter.' Where should you pause?",
      options: [
        "After every word — maximum clarity for non-native audience members",
        "Only at the end of the sentence — internal pauses break the flow",
        "After 'quarter' only — let the sentence run as one continuous stream",
        "After 'percent' (slight pause) and after 'quarter' (full stop) — to mark the key number and the section close",
      ],
      correct: 3,
      explanation:
        "A slight pause after 'percent' separates the key statistic from the timeframe, letting the audience absorb the number before moving on. A full pause after 'quarter' closes the sentence and signals the section transition. Option 1 — pausing after every word — destroys rhythm and sounds robotic. Option 2 — only end pause — makes the statistic run together with the timeframe, losing impact. Option 3 — pause only at end — same flaw as 2, plus the audience never gets a chance to absorb the number. Strategic pauses inside a sentence are what separate presentation speech from rapid conversation.",
    },
    {
      id: "completion",
      type: "completion",
      title: "Presentation Skills Complete!",
      subtitle: "You can now pace a presentation, pause at the right places, and use pitch emphasis to mark key terms. The room will lean in.",
      xp: 165,
      badge: "🎤 Stage Ready",
      nextLessonTitle: "Phone Communication",
    },
  ],
};

export default lesson;
